"""
hedge_fund package
"""

try:
    from .compliance_regulatory import (
        AMLMonitor,
        AlertSeverity,
        ComplianceAlert,
        ComplianceEngine,
        ComplianceStatus,
        Form13F,
        FormPF,
        InvestmentRestrictions,
        RegulatoryReporter,
        RestrictionType,
        TradeCompliance
    )
    from .fund_management import (
        FeeStructure,
        FundManager,
        FundMetrics,
        HighWaterMark,
        Investor,
        InvestorClass,
        InvestorType,
        LockupPeriod,
        NAVCalculator,
        Redemption,
        RedemptionFrequency,
        Subscription
    )
    from .hedge_fund_orchestrator import (
        FundConfig,
        FundState,
        HedgeFundOrchestrator,
        TradingSession,
        create_hedge_fund,
        demo,
        quick_start
    )
    from .institutional_risk import (
        CounterpartyRisk,
        InstitutionalRiskManager,
        LiquidityRisk,
        MarginManager,
        RiskLevel,
        ScenarioAnalysis,
        StressScenario,
        StressTestEngine,
        StressTestResult,
        VaREngine,
        VaRMethod,
        VaRResult
    )
    from .multi_strategy import (
        MultiStrategyEngine,
        Strategy,
        StrategyAllocation,
        StrategyPerformance,
        StrategyRotator,
        StrategyStatus,
        StrategyType
    )
    from .performance_attribution import (
        AttributionMethod,
        BenchmarkTracker,
        BenchmarkType,
        BrinsonAttribution,
        FactorAttribution,
        PeerComparison,
        PerformanceAttributor,
        RiskAdjustedMetrics
    )
    from .portfolio_construction import (
        FactorExposure,
        FactorModel,
        FactorType,
        InstitutionalPortfolioConstructor,
        RebalanceEngine,
        RebalanceMethod,
        RiskBudget,
        TradingCost
    )
    from .prime_broker import (
        BorrowStatus,
        CashManagement,
        CashMovement,
        CashMovementType,
        Custody,
        MarginCalculator,
        MarginLoan,
        PrimeBrokerInterface,
        SecuritiesLending,
        SecuritiesLoan
    )
except ImportError as e:
    import logging
    logging.getLogger(__name__).debug(f'Optional import failed in hedge_fund: {e}')

__all__ = [
    'AMLMonitor',
    'AlertSeverity',
    'AttributionMethod',
    'BenchmarkTracker',
    'BenchmarkType',
    'BorrowStatus',
    'BrinsonAttribution',
    'CashManagement',
    'CashMovement',
    'CashMovementType',
    'ComplianceAlert',
    'ComplianceEngine',
    'ComplianceStatus',
    'CounterpartyRisk',
    'Custody',
    'FactorAttribution',
    'FactorExposure',
    'FactorModel',
    'FactorType',
    'FeeStructure',
    'Form13F',
    'FormPF',
    'FundConfig',
    'FundManager',
    'FundMetrics',
    'FundState',
    'HedgeFundOrchestrator',
    'HighWaterMark',
    'InstitutionalPortfolioConstructor',
    'InstitutionalRiskManager',
    'InvestmentRestrictions',
    'Investor',
    'InvestorClass',
    'InvestorType',
    'LiquidityRisk',
    'LockupPeriod',
    'MarginCalculator',
    'MarginLoan',
    'MarginManager',
    'MultiStrategyEngine',
    'NAVCalculator',
    'PeerComparison',
    'PerformanceAttributor',
    'PrimeBrokerInterface',
    'RebalanceEngine',
    'RebalanceMethod',
    'Redemption',
    'RedemptionFrequency',
    'RegulatoryReporter',
    'RestrictionType',
    'RiskAdjustedMetrics',
    'RiskBudget',
    'RiskLevel',
    'ScenarioAnalysis',
    'SecuritiesLending',
    'SecuritiesLoan',
    'Strategy',
    'StrategyAllocation',
    'StrategyPerformance',
    'StrategyRotator',
    'StrategyStatus',
    'StrategyType',
    'StressScenario',
    'StressTestEngine',
    'StressTestResult',
    'Subscription',
    'TradeCompliance',
    'TradingCost',
    'TradingSession',
    'VaREngine',
    'VaRMethod',
    'VaRResult',
    'create_hedge_fund',
    'demo',
    'quick_start',
]