"""
ingestion package
"""

try:
    from .collector import (
        CollectorConfig,
        CollectorManager,
        CollectorState,
        CollectorStats,
        EXCHANGE_CONFIGS,
        MessageHandler,
        RESTCollector,
        SequenceTracker,
        WebSocketCollector,
        create_collector_config
    )
    from .event_router import (
        CompressionType,
        DeliveryGuarantee,
        EventConsumer,
        EventRouter,
        MockConsumer,
        MockProducer,
        PartitionStrategy,
        RouterConfig,
        TOPIC_CONFIGS,
        TopicConfig,
        TopicResolver
    )
    from .normalizer import (
        BinanceParser,
        CoinbaseParser,
        EventNormalizer,
        ExchangeParser,
        GenericParser,
        NormalizerConfig,
        SequenceValidator,
        TimestampAligner
    )
    from .orchestrator import (
        IngestionOrchestrator,
        OrchestratorConfig,
        PipelineMetrics,
        create_pipeline,
        main,
        setup_signal_handlers
    )
    from .orderbook_builder import (
        LiquidityPersistenceModel,
        OrderBookConfig,
        OrderBookManager,
        OrderBookMode,
        OrderBookState,
        PriceLevel,
        SyntheticOrderBook,
        TradeImbalanceModel
    )
    from .replay_engine import (
        DataSource,
        FileDataSource,
        KafkaDataSource,
        ReplayConfig,
        ReplayCursor,
        ReplayEngine,
        ReplayMode,
        ReplaySession,
        ReplayState
    )
    from .schema import (
        EventEnvelope,
        ExchangeMetadata,
        JSON_SCHEMA,
        L2BookSnapshot,
        L2PriceLevel,
        MarketEvent,
        MarketEventType,
        PROTOBUF_SCHEMA,
        QualityFlag,
        QuoteEvent,
        SCHEMA_MAGIC,
        SCHEMA_VERSION,
        TradeCondition,
        TradeEvent,
        TradeSide
    )
    from .storage import (
        CLICKHOUSE_SCHEMAS,
        ClickHouseWriter,
        MockClickHouseClient,
        S3Archiver,
        StorageBackend,
        StorageConfig,
        StorageManager
    )
except ImportError as e:
    import logging
    logging.getLogger(__name__).debug(f'Optional import failed in ingestion: {e}')

__all__ = [
    'BinanceParser',
    'CLICKHOUSE_SCHEMAS',
    'ClickHouseWriter',
    'CoinbaseParser',
    'CollectorConfig',
    'CollectorManager',
    'CollectorState',
    'CollectorStats',
    'CompressionType',
    'DataSource',
    'DeliveryGuarantee',
    'EXCHANGE_CONFIGS',
    'EventConsumer',
    'EventEnvelope',
    'EventNormalizer',
    'EventRouter',
    'ExchangeMetadata',
    'ExchangeParser',
    'FileDataSource',
    'GenericParser',
    'IngestionOrchestrator',
    'JSON_SCHEMA',
    'KafkaDataSource',
    'L2BookSnapshot',
    'L2PriceLevel',
    'LiquidityPersistenceModel',
    'MarketEvent',
    'MarketEventType',
    'MessageHandler',
    'MockClickHouseClient',
    'MockConsumer',
    'MockProducer',
    'NormalizerConfig',
    'OrchestratorConfig',
    'OrderBookConfig',
    'OrderBookManager',
    'OrderBookMode',
    'OrderBookState',
    'PROTOBUF_SCHEMA',
    'PartitionStrategy',
    'PipelineMetrics',
    'PriceLevel',
    'QualityFlag',
    'QuoteEvent',
    'RESTCollector',
    'ReplayConfig',
    'ReplayCursor',
    'ReplayEngine',
    'ReplayMode',
    'ReplaySession',
    'ReplayState',
    'RouterConfig',
    'S3Archiver',
    'SCHEMA_MAGIC',
    'SCHEMA_VERSION',
    'SequenceTracker',
    'SequenceValidator',
    'StorageBackend',
    'StorageConfig',
    'StorageManager',
    'SyntheticOrderBook',
    'TOPIC_CONFIGS',
    'TimestampAligner',
    'TopicConfig',
    'TopicResolver',
    'TradeCondition',
    'TradeEvent',
    'TradeImbalanceModel',
    'TradeSide',
    'WebSocketCollector',
    'create_collector_config',
    'create_pipeline',
    'main',
    'setup_signal_handlers',
]