"""
NEUROS-FI Region 1: Neocortex - Six-Layer Predictive Coding Hierarchy
======================================================================

Biological Basis:
The cortex runs a hierarchy of prediction machines. Layer IV receives bottom-up
sensory data. Layers II/III transmit lateral predictions. Layers V/VI send
top-down predictions back down. Only prediction errors propagate upward — not
raw data. This is maximally efficient: the system transmits only surprise.

Citations:
- Rao & Ballard (1999) - Predictive coding in the visual cortex
- Friston (2005) - A theory of cortical responses
- Bastos et al. (2012) - Canonical microcircuits for predictive coding
- Clark (2013) - Whatever next? Predictive brains, situated agents

Cortical Layer Mapping:
- Layer VI: Decades (monetary regime priors, secular cycles)
- Layer V: Years-Months (portfolio construction, strategic regime)
- Layer IV: Weeks-Days (thalamic input relay)
- Layer III: Days-Hours (cross-asset pattern recognition)
- Layer II: Hours-Minutes (intraday signal processing)
- Layer I: Minutes-Nanoseconds (execution response)

Constitutional Version: 5.0
"""

import logging
import math
import threading
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum, auto
from typing import Any, Callable, Dict, List, Optional, Tuple
import numpy as np

logger = logging.getLogger(__name__)


class CorticalLayerType(Enum):
    """The six cortical layers with their temporal horizons."""
    
    LAYER_I = auto()    # Minutes-Nanoseconds: Execution response
    LAYER_II = auto()   # Hours-Minutes: Intraday signals
    LAYER_III = auto()  # Days-Hours: Cross-asset patterns
    LAYER_IV = auto()   # Weeks-Days: Thalamic input relay
    LAYER_V = auto()    # Years-Months: Portfolio construction
    LAYER_VI = auto()   # Decades: Monetary regime priors


class PredictionErrorType(Enum):
    """Types of prediction errors in the hierarchy."""
    
    SENSORY = auto()      # Bottom-up sensory mismatch
    PRECISION = auto()    # Uncertainty in prediction
    TEMPORAL = auto()     # Timing mismatch
    STRUCTURAL = auto()   # Model structure mismatch


@dataclass
class Prediction:
    """A prediction generated by a cortical layer."""
    
    layer: CorticalLayerType
    timestamp: datetime
    target_variable: str
    predicted_value: float
    confidence: float  # 0-1
    precision: float   # Inverse variance (higher = more certain)
    time_horizon: timedelta
    context: Dict[str, Any] = field(default_factory=dict)
    prediction_id: str = ""
    
    def __post_init__(self):
        if not self.prediction_id:
            self.prediction_id = f"pred_{self.layer.name}_{int(time.time()*1000)}"


@dataclass
class PredictionError:
    """A prediction error that propagates upward through the hierarchy."""
    
    error_type: PredictionErrorType
    source_layer: CorticalLayerType
    timestamp: datetime
    prediction: Prediction
    observed_value: float
    error_magnitude: float  # Absolute error
    precision_weighted_error: float  # Error weighted by precision
    surprise: float  # -log p(observation | prediction)
    propagate_upward: bool = True
    
    def __post_init__(self):
        # Calculate surprise (negative log probability)
        # Higher precision predictions that are wrong generate more surprise
        if self.error_magnitude > 0:
            self.surprise = self.precision_weighted_error * math.log(1 + self.error_magnitude)


@dataclass
class CorticalColumnState:
    """State of a cortical column (asset-class specialized processor)."""
    
    column_id: str
    asset_class: str
    active_predictions: List[Prediction] = field(default_factory=list)
    pending_errors: List[PredictionError] = field(default_factory=list)
    layer_activations: Dict[CorticalLayerType, float] = field(default_factory=dict)
    last_update: datetime = field(default_factory=datetime.utcnow)


class CorticalLayer(ABC):
    """
    Abstract base class for a cortical layer in the predictive coding hierarchy.
    
    Each layer:
    1. Receives bottom-up input from the layer below
    2. Generates predictions for the layer below
    3. Receives top-down predictions from the layer above
    4. Computes prediction errors and propagates them upward
    """
    
    def __init__(
        self,
        layer_type: CorticalLayerType,
        time_horizon: timedelta,
        precision_prior: float = 1.0
    ):
        self.layer_type = layer_type
        self.time_horizon = time_horizon
        self.precision_prior = precision_prior
        
        # Layer state
        self._predictions: Dict[str, Prediction] = {}
        self._errors: List[PredictionError] = []
        self._weights: Dict[str, float] = {}
        self._learning_rate: float = 0.01
        
        # Connections
        self._layer_above: Optional['CorticalLayer'] = None
        self._layer_below: Optional['CorticalLayer'] = None
        
        # Plasticity state (for STDP)
        self._recent_activations: List[Tuple[datetime, float]] = []
        self._plasticity_window = timedelta(seconds=1)
    
    @abstractmethod
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Generate a prediction for the layer below."""
        pass
    
    @abstractmethod
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process input from the layer below, compute prediction error."""
        pass
    
    def receive_top_down_prediction(self, prediction: Prediction):
        """Receive a prediction from the layer above as context."""
        self._predictions[prediction.target_variable] = prediction
    
    def propagate_error_upward(self, error: PredictionError):
        """Propagate a prediction error to the layer above."""
        if self._layer_above and error.propagate_upward:
            self._layer_above.receive_error_from_below(error)
    
    def receive_error_from_below(self, error: PredictionError):
        """Receive an error from the layer below for learning."""
        self._errors.append(error)
        self._update_weights(error)
    
    def _update_weights(self, error: PredictionError):
        """Update weights based on prediction error (Hebbian learning)."""
        # Precision-weighted error drives learning
        learning_signal = error.precision_weighted_error * self._learning_rate
        
        # Update relevant weights
        for key in self._weights:
            if key in error.prediction.context:
                # Hebbian: strengthen connections that predicted correctly
                # Anti-Hebbian: weaken connections that predicted incorrectly
                self._weights[key] -= learning_signal * error.prediction.context[key]
    
    def connect_to_layer_above(self, layer: 'CorticalLayer'):
        """Connect to the layer above in the hierarchy."""
        self._layer_above = layer
        layer._layer_below = self
    
    def get_free_energy(self) -> float:
        """
        Calculate the free energy (total prediction error) for this layer.
        
        F = D_KL[q(s) || p(s|o)] - ln p(o)
        
        In practice: sum of precision-weighted squared errors
        """
        if not self._errors:
            return 0.0
        
        return sum(e.precision_weighted_error ** 2 for e in self._errors[-100:])


class LayerI_Execution(CorticalLayer):
    """
    Layer I: Minutes-Nanoseconds - Execution Response
    
    The fastest layer, handling microstructure adaptation and order routing.
    Runs in co-located execution facility.
    """
    
    def __init__(self):
        super().__init__(
            layer_type=CorticalLayerType.LAYER_I,
            time_horizon=timedelta(minutes=1),
            precision_prior=10.0  # High precision for execution
        )
        
        # Execution-specific state
        self._order_book_state: Dict[str, Any] = {}
        self._microstructure_model: Dict[str, float] = {}
        self._execution_latency_ms: float = 0.0
    
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Predict execution outcome (fill probability, slippage)."""
        
        # Extract order details
        order_size = input_data.get('order_size', 0)
        spread = input_data.get('spread', 0.0001)
        volatility = input_data.get('volatility', 0.01)
        
        # Simple execution cost prediction
        predicted_slippage = spread * 0.5 + volatility * order_size * 0.0001
        
        return Prediction(
            layer=self.layer_type,
            timestamp=datetime.utcnow(),
            target_variable='execution_cost',
            predicted_value=predicted_slippage,
            confidence=0.8,
            precision=self.precision_prior,
            time_horizon=self.time_horizon,
            context=input_data,
        )
    
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process actual execution outcome, compute error."""
        
        actual_cost = input_data.get('actual_execution_cost', 0)
        prediction = self._predictions.get('execution_cost')
        
        if prediction is None:
            return None
        
        error_magnitude = abs(actual_cost - prediction.predicted_value)
        precision_weighted = error_magnitude * prediction.precision
        
        return PredictionError(
            error_type=PredictionErrorType.SENSORY,
            source_layer=self.layer_type,
            timestamp=datetime.utcnow(),
            prediction=prediction,
            observed_value=actual_cost,
            error_magnitude=error_magnitude,
            precision_weighted_error=precision_weighted,
            surprise=0.0,  # Calculated in __post_init__
        )


class LayerII_Intraday(CorticalLayer):
    """
    Layer II: Hours-Minutes - Intraday Signal Processing
    
    Short-horizon alpha models and real-time signal integration.
    """
    
    def __init__(self):
        super().__init__(
            layer_type=CorticalLayerType.LAYER_II,
            time_horizon=timedelta(hours=4),
            precision_prior=5.0
        )
        
        # Intraday signal state
        self._active_signals: Dict[str, float] = {}
        self._signal_weights: Dict[str, float] = {}
    
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Generate intraday price movement prediction."""
        
        # Aggregate signals
        signals = input_data.get('signals', {})
        weights = self._signal_weights
        
        # Weighted signal combination
        if signals and weights:
            prediction_value = sum(
                signals.get(k, 0) * weights.get(k, 1.0)
                for k in signals
            ) / max(len(signals), 1)
        else:
            prediction_value = 0.0
        
        # Adjust for top-down context (regime from Layer V)
        if top_down_context:
            regime_adjustment = top_down_context.get('regime_adjustment', 1.0)
            prediction_value *= regime_adjustment
        
        return Prediction(
            layer=self.layer_type,
            timestamp=datetime.utcnow(),
            target_variable='intraday_return',
            predicted_value=prediction_value,
            confidence=0.6,
            precision=self.precision_prior,
            time_horizon=self.time_horizon,
            context={'signals': signals},
        )
    
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process actual intraday returns, compute error."""
        
        actual_return = input_data.get('actual_return', 0)
        prediction = self._predictions.get('intraday_return')
        
        if prediction is None:
            return None
        
        error_magnitude = abs(actual_return - prediction.predicted_value)
        precision_weighted = error_magnitude * prediction.precision
        
        error = PredictionError(
            error_type=PredictionErrorType.SENSORY,
            source_layer=self.layer_type,
            timestamp=datetime.utcnow(),
            prediction=prediction,
            observed_value=actual_return,
            error_magnitude=error_magnitude,
            precision_weighted_error=precision_weighted,
            surprise=0.0,
        )
        
        # Propagate significant errors upward
        if error_magnitude > 0.01:  # 1% threshold
            error.propagate_upward = True
        
        return error


class LayerIII_CrossAsset(CorticalLayer):
    """
    Layer III: Days-Hours - Cross-Asset Pattern Recognition
    
    Factor model predictions and cross-asset correlations.
    """
    
    def __init__(self):
        super().__init__(
            layer_type=CorticalLayerType.LAYER_III,
            time_horizon=timedelta(days=1),
            precision_prior=3.0
        )
        
        # Factor model state
        self._factor_exposures: Dict[str, Dict[str, float]] = {}
        self._correlation_matrix: Optional[np.ndarray] = None
        self._factor_returns: Dict[str, float] = {}
    
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Generate cross-asset factor-based prediction."""
        
        # Extract factor exposures
        exposures = input_data.get('factor_exposures', {})
        factor_predictions = input_data.get('factor_predictions', {})
        
        # Factor model prediction
        predicted_return = sum(
            exposures.get(f, 0) * factor_predictions.get(f, 0)
            for f in exposures
        )
        
        # Adjust for strategic context from Layer V
        if top_down_context:
            strategic_tilt = top_down_context.get('strategic_tilt', 0)
            predicted_return += strategic_tilt
        
        return Prediction(
            layer=self.layer_type,
            timestamp=datetime.utcnow(),
            target_variable='factor_return',
            predicted_value=predicted_return,
            confidence=0.5,
            precision=self.precision_prior,
            time_horizon=self.time_horizon,
            context={'exposures': exposures},
        )
    
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process actual factor returns, compute error."""
        
        actual_return = input_data.get('actual_factor_return', 0)
        prediction = self._predictions.get('factor_return')
        
        if prediction is None:
            return None
        
        error_magnitude = abs(actual_return - prediction.predicted_value)
        precision_weighted = error_magnitude * prediction.precision
        
        return PredictionError(
            error_type=PredictionErrorType.SENSORY,
            source_layer=self.layer_type,
            timestamp=datetime.utcnow(),
            prediction=prediction,
            observed_value=actual_return,
            error_magnitude=error_magnitude,
            precision_weighted_error=precision_weighted,
            surprise=0.0,
        )


class LayerIV_ThalamicRelay(CorticalLayer):
    """
    Layer IV: Weeks-Days - Thalamic Input Relay
    
    The gateway layer - all sensory input passes through here.
    Integrates signals from all data feeds before cortical processing.
    """
    
    def __init__(self):
        super().__init__(
            layer_type=CorticalLayerType.LAYER_IV,
            time_horizon=timedelta(weeks=1),
            precision_prior=2.0
        )
        
        # Input relay state
        self._data_feeds: Dict[str, Dict[str, Any]] = {}
        self._feed_quality: Dict[str, float] = {}
        self._integration_weights: Dict[str, float] = {}
    
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Generate integrated market state prediction."""
        
        # Integrate multiple data feeds
        feeds = input_data.get('feeds', {})
        
        # Quality-weighted integration
        integrated_signal = 0.0
        total_weight = 0.0
        
        for feed_id, feed_data in feeds.items():
            quality = self._feed_quality.get(feed_id, 0.5)
            weight = self._integration_weights.get(feed_id, 1.0) * quality
            
            signal = feed_data.get('signal', 0)
            integrated_signal += signal * weight
            total_weight += weight
        
        if total_weight > 0:
            integrated_signal /= total_weight
        
        return Prediction(
            layer=self.layer_type,
            timestamp=datetime.utcnow(),
            target_variable='integrated_signal',
            predicted_value=integrated_signal,
            confidence=0.4,
            precision=self.precision_prior,
            time_horizon=self.time_horizon,
            context={'feed_count': len(feeds)},
        )
    
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process integrated signal outcome."""
        
        actual_signal = input_data.get('actual_integrated_signal', 0)
        prediction = self._predictions.get('integrated_signal')
        
        if prediction is None:
            return None
        
        error_magnitude = abs(actual_signal - prediction.predicted_value)
        precision_weighted = error_magnitude * prediction.precision
        
        return PredictionError(
            error_type=PredictionErrorType.SENSORY,
            source_layer=self.layer_type,
            timestamp=datetime.utcnow(),
            prediction=prediction,
            observed_value=actual_signal,
            error_magnitude=error_magnitude,
            precision_weighted_error=precision_weighted,
            surprise=0.0,
        )
    
    def update_feed_quality(self, feed_id: str, quality: float):
        """Update the quality score for a data feed."""
        self._feed_quality[feed_id] = max(0.0, min(1.0, quality))


class LayerV_Portfolio(CorticalLayer):
    """
    Layer V: Years-Months - Portfolio Construction
    
    Strategic regime models and cross-strategy capital allocation.
    Output layer to portfolio construction.
    """
    
    def __init__(self):
        super().__init__(
            layer_type=CorticalLayerType.LAYER_V,
            time_horizon=timedelta(days=90),
            precision_prior=1.0
        )
        
        # Portfolio state
        self._strategy_allocations: Dict[str, float] = {}
        self._regime_state: str = "normal"
        self._risk_budget: float = 1.0
    
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Generate strategic portfolio prediction."""
        
        # Extract strategy performance
        strategy_returns = input_data.get('strategy_returns', {})
        regime = input_data.get('regime', 'normal')
        
        # Regime-conditional expected return
        regime_multipliers = {
            'bull': 1.2,
            'normal': 1.0,
            'bear': 0.6,
            'crisis': 0.2,
        }
        
        base_return = sum(strategy_returns.values()) / max(len(strategy_returns), 1)
        regime_adjusted = base_return * regime_multipliers.get(regime, 1.0)
        
        # Adjust for secular context from Layer VI
        if top_down_context:
            secular_adjustment = top_down_context.get('secular_adjustment', 1.0)
            regime_adjusted *= secular_adjustment
        
        self._regime_state = regime
        
        return Prediction(
            layer=self.layer_type,
            timestamp=datetime.utcnow(),
            target_variable='portfolio_return',
            predicted_value=regime_adjusted,
            confidence=0.3,
            precision=self.precision_prior,
            time_horizon=self.time_horizon,
            context={'regime': regime},
        )
    
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process actual portfolio returns."""
        
        actual_return = input_data.get('actual_portfolio_return', 0)
        prediction = self._predictions.get('portfolio_return')
        
        if prediction is None:
            return None
        
        error_magnitude = abs(actual_return - prediction.predicted_value)
        precision_weighted = error_magnitude * prediction.precision
        
        return PredictionError(
            error_type=PredictionErrorType.SENSORY,
            source_layer=self.layer_type,
            timestamp=datetime.utcnow(),
            prediction=prediction,
            observed_value=actual_return,
            error_magnitude=error_magnitude,
            precision_weighted_error=precision_weighted,
            surprise=0.0,
        )
    
    def get_regime_adjustment(self) -> float:
        """Get regime adjustment for lower layers."""
        adjustments = {
            'bull': 1.2,
            'normal': 1.0,
            'bear': 0.7,
            'crisis': 0.3,
        }
        return adjustments.get(self._regime_state, 1.0)


class LayerVI_Secular(CorticalLayer):
    """
    Layer VI: Decades - Monetary Regime Priors
    
    The slowest layer, holding secular demographic cycles and
    long-run factor models. Provides top-down context to all layers.
    """
    
    def __init__(self):
        super().__init__(
            layer_type=CorticalLayerType.LAYER_VI,
            time_horizon=timedelta(days=3650),  # ~10 years
            precision_prior=0.5  # Low precision for long-horizon
        )
        
        # Secular state
        self._monetary_regime: str = "normal"
        self._secular_cycle_phase: str = "expansion"
        self._demographic_factors: Dict[str, float] = {}
        self._long_run_priors: Dict[str, float] = {
            'equity_premium': 0.05,
            'bond_return': 0.02,
            'inflation': 0.02,
        }
    
    def generate_prediction(
        self,
        input_data: Dict[str, Any],
        top_down_context: Optional[Dict[str, Any]] = None
    ) -> Prediction:
        """Generate secular/long-run prediction."""
        
        # Extract macro indicators
        inflation = input_data.get('inflation', 0.02)
        growth = input_data.get('gdp_growth', 0.02)
        policy_rate = input_data.get('policy_rate', 0.03)
        
        # Secular cycle adjustment
        cycle_adjustments = {
            'expansion': 1.1,
            'peak': 0.9,
            'contraction': 0.7,
            'trough': 1.0,
        }
        
        # Long-run expected return
        base_return = self._long_run_priors['equity_premium']
        secular_adjusted = base_return * cycle_adjustments.get(
            self._secular_cycle_phase, 1.0
        )
        
        # Inflation adjustment
        real_return = secular_adjusted - inflation
        
        return Prediction(
            layer=self.layer_type,
            timestamp=datetime.utcnow(),
            target_variable='secular_return',
            predicted_value=real_return,
            confidence=0.2,  # Low confidence for long horizon
            precision=self.precision_prior,
            time_horizon=self.time_horizon,
            context={
                'monetary_regime': self._monetary_regime,
                'secular_cycle': self._secular_cycle_phase,
            },
        )
    
    def process_bottom_up_input(
        self,
        input_data: Dict[str, Any]
    ) -> Optional[PredictionError]:
        """Process long-run return realization."""
        
        actual_return = input_data.get('actual_secular_return', 0)
        prediction = self._predictions.get('secular_return')
        
        if prediction is None:
            return None
        
        error_magnitude = abs(actual_return - prediction.predicted_value)
        precision_weighted = error_magnitude * prediction.precision
        
        # Secular errors are significant - always propagate
        return PredictionError(
            error_type=PredictionErrorType.STRUCTURAL,
            source_layer=self.layer_type,
            timestamp=datetime.utcnow(),
            prediction=prediction,
            observed_value=actual_return,
            error_magnitude=error_magnitude,
            precision_weighted_error=precision_weighted,
            surprise=0.0,
            propagate_upward=False,  # Top layer - nowhere to propagate
        )
    
    def update_secular_state(
        self,
        monetary_regime: Optional[str] = None,
        secular_cycle: Optional[str] = None
    ):
        """Update secular state based on macro analysis."""
        if monetary_regime:
            self._monetary_regime = monetary_regime
        if secular_cycle:
            self._secular_cycle_phase = secular_cycle
    
    def get_secular_adjustment(self) -> float:
        """Get secular adjustment for lower layers."""
        cycle_adjustments = {
            'expansion': 1.1,
            'peak': 0.85,
            'contraction': 0.6,
            'trough': 0.9,
        }
        return cycle_adjustments.get(self._secular_cycle_phase, 1.0)


class PredictiveCodingHierarchy:
    """
    The complete six-layer predictive coding hierarchy.
    
    Implements the cortical microcircuit where:
    - Higher layers generate predictions for lower layers
    - Lower layers compute prediction errors
    - Only prediction errors propagate upward
    - Learning minimizes free energy (prediction error)
    """
    
    def __init__(self):
        # Initialize all six layers
        self.layer_i = LayerI_Execution()
        self.layer_ii = LayerII_Intraday()
        self.layer_iii = LayerIII_CrossAsset()
        self.layer_iv = LayerIV_ThalamicRelay()
        self.layer_v = LayerV_Portfolio()
        self.layer_vi = LayerVI_Secular()
        
        # Connect layers in hierarchy
        self.layer_i.connect_to_layer_above(self.layer_ii)
        self.layer_ii.connect_to_layer_above(self.layer_iii)
        self.layer_iii.connect_to_layer_above(self.layer_iv)
        self.layer_iv.connect_to_layer_above(self.layer_v)
        self.layer_v.connect_to_layer_above(self.layer_vi)
        
        # Layer lookup
        self._layers = {
            CorticalLayerType.LAYER_I: self.layer_i,
            CorticalLayerType.LAYER_II: self.layer_ii,
            CorticalLayerType.LAYER_III: self.layer_iii,
            CorticalLayerType.LAYER_IV: self.layer_iv,
            CorticalLayerType.LAYER_V: self.layer_v,
            CorticalLayerType.LAYER_VI: self.layer_vi,
        }
        
        # Hierarchy state
        self._total_free_energy: float = 0.0
        self._prediction_count: int = 0
        self._error_count: int = 0
        
        logger.info("Predictive Coding Hierarchy initialized - 6 layers connected")
    
    def top_down_pass(self, macro_context: Dict[str, Any]) -> Dict[str, Prediction]:
        """
        Execute top-down prediction pass through the hierarchy.
        
        Starting from Layer VI (secular), generate predictions that
        propagate down to Layer I (execution).
        """
        predictions = {}
        
        # Layer VI generates secular prediction
        pred_vi = self.layer_vi.generate_prediction(macro_context)
        predictions['layer_vi'] = pred_vi
        
        # Layer V receives secular context, generates portfolio prediction
        context_v = {'secular_adjustment': self.layer_vi.get_secular_adjustment()}
        pred_v = self.layer_v.generate_prediction(
            macro_context.get('portfolio', {}),
            top_down_context=context_v
        )
        predictions['layer_v'] = pred_v
        self.layer_v.receive_top_down_prediction(pred_vi)
        
        # Layer IV receives portfolio context
        context_iv = {'regime_adjustment': self.layer_v.get_regime_adjustment()}
        pred_iv = self.layer_iv.generate_prediction(
            macro_context.get('feeds', {}),
            top_down_context=context_iv
        )
        predictions['layer_iv'] = pred_iv
        self.layer_iv.receive_top_down_prediction(pred_v)
        
        # Layer III receives integrated signal context
        pred_iii = self.layer_iii.generate_prediction(
            macro_context.get('factors', {}),
            top_down_context=context_iv
        )
        predictions['layer_iii'] = pred_iii
        self.layer_iii.receive_top_down_prediction(pred_iv)
        
        # Layer II receives factor context
        pred_ii = self.layer_ii.generate_prediction(
            macro_context.get('signals', {}),
            top_down_context=context_iv
        )
        predictions['layer_ii'] = pred_ii
        self.layer_ii.receive_top_down_prediction(pred_iii)
        
        # Layer I receives intraday context
        pred_i = self.layer_i.generate_prediction(
            macro_context.get('execution', {}),
            top_down_context={'intraday_prediction': pred_ii.predicted_value}
        )
        predictions['layer_i'] = pred_i
        self.layer_i.receive_top_down_prediction(pred_ii)
        
        self._prediction_count += 6
        
        return predictions
    
    def bottom_up_pass(self, observations: Dict[str, Any]) -> List[PredictionError]:
        """
        Execute bottom-up error propagation through the hierarchy.
        
        Starting from Layer I (execution), compute prediction errors
        and propagate them upward to higher layers.
        """
        errors = []
        
        # Layer I processes execution outcome
        error_i = self.layer_i.process_bottom_up_input(
            observations.get('execution', {})
        )
        if error_i:
            errors.append(error_i)
            self.layer_i.propagate_error_upward(error_i)
        
        # Layer II processes intraday outcome
        error_ii = self.layer_ii.process_bottom_up_input(
            observations.get('intraday', {})
        )
        if error_ii:
            errors.append(error_ii)
            self.layer_ii.propagate_error_upward(error_ii)
        
        # Layer III processes factor outcome
        error_iii = self.layer_iii.process_bottom_up_input(
            observations.get('factors', {})
        )
        if error_iii:
            errors.append(error_iii)
            self.layer_iii.propagate_error_upward(error_iii)
        
        # Layer IV processes integrated signal outcome
        error_iv = self.layer_iv.process_bottom_up_input(
            observations.get('integrated', {})
        )
        if error_iv:
            errors.append(error_iv)
            self.layer_iv.propagate_error_upward(error_iv)
        
        # Layer V processes portfolio outcome
        error_v = self.layer_v.process_bottom_up_input(
            observations.get('portfolio', {})
        )
        if error_v:
            errors.append(error_v)
            self.layer_v.propagate_error_upward(error_v)
        
        # Layer VI processes secular outcome
        error_vi = self.layer_vi.process_bottom_up_input(
            observations.get('secular', {})
        )
        if error_vi:
            errors.append(error_vi)
        
        self._error_count += len(errors)
        self._update_free_energy()
        
        return errors
    
    def _update_free_energy(self):
        """Update total free energy across all layers."""
        self._total_free_energy = sum(
            layer.get_free_energy() for layer in self._layers.values()
        )
    
    def get_free_energy(self) -> float:
        """Get total free energy (prediction error) across hierarchy."""
        return self._total_free_energy
    
    def get_layer(self, layer_type: CorticalLayerType) -> CorticalLayer:
        """Get a specific layer by type."""
        return self._layers[layer_type]
    
    def get_status(self) -> Dict[str, Any]:
        """Get hierarchy status."""
        return {
            'total_free_energy': self._total_free_energy,
            'prediction_count': self._prediction_count,
            'error_count': self._error_count,
            'layer_free_energies': {
                layer_type.name: layer.get_free_energy()
                for layer_type, layer in self._layers.items()
            },
        }


class Neocortex:
    """
    The complete Neocortex - six cortical columns (asset classes)
    each running the six-layer predictive coding hierarchy.
    
    Columns communicate horizontally via Layers II and III.
    """
    
    def __init__(self):
        # Six cortical columns for different asset classes
        self.columns: Dict[str, PredictiveCodingHierarchy] = {
            'equities': PredictiveCodingHierarchy(),
            'fixed_income': PredictiveCodingHierarchy(),
            'fx': PredictiveCodingHierarchy(),
            'credit': PredictiveCodingHierarchy(),
            'commodities': PredictiveCodingHierarchy(),
            'macro': PredictiveCodingHierarchy(),
        }
        
        # Inter-column connections (Layers II/III)
        self._cross_column_weights: Dict[Tuple[str, str], float] = {}
        self._initialize_cross_column_weights()
        
        # Global state
        self._lock = threading.RLock()
        self._total_free_energy: float = 0.0
        
        logger.info("Neocortex initialized - 6 cortical columns active")
    
    def _initialize_cross_column_weights(self):
        """Initialize cross-column connection weights."""
        columns = list(self.columns.keys())
        for i, col1 in enumerate(columns):
            for col2 in columns[i+1:]:
                # Default correlation-based weights
                self._cross_column_weights[(col1, col2)] = 0.3
                self._cross_column_weights[(col2, col1)] = 0.3
    
    def process_market_data(
        self,
        data: Dict[str, Dict[str, Any]]
    ) -> Dict[str, Any]:
        """
        Process market data through all cortical columns.
        
        Args:
            data: Dict mapping asset class to market data
            
        Returns:
            Integrated predictions and errors
        """
        with self._lock:
            all_predictions = {}
            all_errors = []
            
            # Top-down pass through each column
            for asset_class, column in self.columns.items():
                column_data = data.get(asset_class, {})
                predictions = column.top_down_pass(column_data)
                all_predictions[asset_class] = predictions
            
            # Cross-column signal sharing (Layers II/III)
            self._share_cross_column_signals(all_predictions)
            
            # Bottom-up pass through each column
            for asset_class, column in self.columns.items():
                column_data = data.get(asset_class, {})
                errors = column.bottom_up_pass(column_data)
                all_errors.extend(errors)
            
            # Update total free energy
            self._total_free_energy = sum(
                col.get_free_energy() for col in self.columns.values()
            )
            
            return {
                'predictions': all_predictions,
                'errors': all_errors,
                'total_free_energy': self._total_free_energy,
            }
    
    def _share_cross_column_signals(
        self,
        predictions: Dict[str, Dict[str, Prediction]]
    ):
        """Share signals between columns via Layers II/III."""
        # Extract Layer II/III predictions from each column
        for (col1, col2), weight in self._cross_column_weights.items():
            if col1 in predictions and col2 in predictions:
                # Share Layer III (cross-asset) predictions
                pred_col1 = predictions[col1].get('layer_iii')
                pred_col2 = predictions[col2].get('layer_iii')
                
                if pred_col1 and pred_col2:
                    # Weighted signal sharing
                    shared_signal = (
                        pred_col1.predicted_value * weight +
                        pred_col2.predicted_value * (1 - weight)
                    )
                    # Update both columns' context
                    self.columns[col1].layer_iii._predictions[f'{col2}_signal'] = Prediction(
                        layer=CorticalLayerType.LAYER_III,
                        timestamp=datetime.utcnow(),
                        target_variable=f'{col2}_cross_signal',
                        predicted_value=shared_signal,
                        confidence=0.4,
                        precision=1.0,
                        time_horizon=timedelta(days=1),
                    )
    
    def get_column(self, asset_class: str) -> PredictiveCodingHierarchy:
        """Get a specific cortical column."""
        return self.columns.get(asset_class)
    
    def get_total_free_energy(self) -> float:
        """Get total free energy across all columns."""
        return self._total_free_energy
    
    def get_status(self) -> Dict[str, Any]:
        """Get neocortex status."""
        return {
            'total_free_energy': self._total_free_energy,
            'column_count': len(self.columns),
            'columns': {
                name: col.get_status()
                for name, col in self.columns.items()
            },
        }
