"""Stable AlphaAlgo domain contracts and adapter ports."""

from .capability_registry import CapabilityRegistration, CapabilityRegistry
from .contracts import (
    ApprovalDecision,
    AuditEvent,
    DataQuality,
    DecisionProposal,
    ExecutionReport,
    Exposure,
    Fill,
    Instrument,
    InstrumentType,
    MarketEvent,
    MarketEventType,
    OrderRequest,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioSnapshot,
    Position,
    ReconciliationResult,
    RiskDecision,
    RiskState,
    Signal,
    Venue,
)
from .ports import (
    AgentCapabilityPort,
    BrokerAdapter,
    ComponentLifecycle,
    ExecutionService,
    MarketDataAdapter,
    PortfolioRepository,
    RiskPolicy,
    RiskService,
    StrategyPort,
    TradingRepository,
    WorldModelPort,
)

__all__ = [
    "AgentCapabilityPort",
    "CapabilityRegistration",
    "CapabilityRegistry",
    "ApprovalDecision",
    "AuditEvent",
    "BrokerAdapter",
    "ComponentLifecycle",
    "DataQuality",
    "DecisionProposal",
    "ExecutionReport",
    "ExecutionService",
    "Exposure",
    "Fill",
    "Instrument",
    "InstrumentType",
    "MarketDataAdapter",
    "MarketEvent",
    "MarketEventType",
    "OrderRequest",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PortfolioRepository",
    "PortfolioSnapshot",
    "Position",
    "ReconciliationResult",
    "RiskDecision",
    "RiskPolicy",
    "RiskService",
    "RiskState",
    "StrategyPort",
    "TradingRepository",
    "Signal",
    "Venue",
    "WorldModelPort",
]
